Fix chunking bug with compound dtypes
catalystneuro/neuroconv pull request #1146
Opened 2024-11-22 18:28 UTC by pauladkisson

Fixes #1122

2024-12-05 00:50 UTC, pauladkisson commented
@rly, lmk what you think

2025-01-27 19:12 UTC, pauladkisson commented
@h-mayorquin, this is ready for review. Basically I use the hdmf.build.builders.BaseBuilder to check if a neurodata object would have a compound dtype. Most of the complexity is introduced by the need to find a match between the neurodata object and its location in the builder, which is outlined in the docstrings. Lmk what you think!

2025-02-06 01:32 UTC, h-mayorquin commented
I did a first reading. Two things:
* I think, we should update hdmf on the pyproject to the latest version or greater.
* Looking at the tests that were failing before they seem related to the pixel mask. Can we create a more direct test of this in the dataset configuration tests? I think it would be better to have something more unit-test-like that would fail quicker if we break this (or if we can to refactor). Can we build something simpler with pixel-mask so we don't rely on the full segmentation conversion test?

2025-02-06 02:25 UTC, pauladkisson commented
> I think, we should update hdmf on the pyproject to the latest version or greater.

I updated to include everything <4, which zarr-related issues. Should be able to add hdmf 4.0 soon -- see: #1191

2025-02-06 02:27 UTC, pauladkisson commented
> Looking at the tests that were failing before they seem related to the pixel mask. Can we create a more direct test of this in the dataset configuration tests? I think it would be better to have something more unit-test-like that would fail quicker if we break this (or if we can to refactor). Can we build something simpler with pixel-mask so we don't rely on the full segmentation conversion test?

Definitely needs some unit tests. I'll put together some.

2025-02-06 17:26 UTC, pauladkisson commented
From Meeting: move has_compound_dtype inside get_data_shape

2025-02-06 21:50 UTC, pauladkisson commented
> From Meeting: move has_compound_dtype inside get_data_shape

Actually, `get_data_shape` comes from hdmf.utils, so no way to move that in this PR. Also, if I remember correctly, they use `get_data_shape` in ways that would make incorporating this compound_dtype fix difficult.

2025-02-06 21:50 UTC, pauladkisson commented
@h-mayorquin, i added tests, so this should be good to go!

2025-02-13 19:45 UTC, h-mayorquin requested changes
My apologies regarding the `get_data_shape` function.

I propose we create a new function called `get_full_data_shape` in `src/neuroconv/tools/hdmf.py` and consolidate all related functionality there. It seems that this should be something provided by HDMF, and isolating this complexity from the rest of the code would be ideal.

There is also a coupling issue with the calculation of the manager for the entire file. I would prefer not to require `from_neurodata_object` to accept an additional argument that is build related. However, calculating the manager for every dataset is probably too expensive, and using the manager to build only for the dataset doesn't work (based on my initial attempt).

**Requests:**

1. **Centralize Logic:**  
   Move the code to HDMF in the `tools` directory and create a new function, `get_full_shape`, that takes the builder as an optional argument so that all the logic is centralized. In the docstring, document that `get_data_shape` fails for compound objects and that this behavior is desired for building a dataset I/O configuration object.

2. **Add Tests:**  
   Add a test that asserts the correct behavior of either the new function `get_dataset_full_shape` or the dataset IO configuration produced by the `from_neurodata_object` method. See the more concrete request on the review.

2025-02-13 19:45 UTC, h-mayorquin commented on src/neuroconv/tools/nwb_helpers/_configuration_models/_base_dataset_io.py
> +    def from_neurodata_object(
I would like to make the builder argument optional. If the builder is not passed, then the check for a compound object is not performed.

Reasons:
1. We might find a better way to handle this in the future, and I want to avoid breaking backwards compatibility if that happens.
2. I want a quick way to test the effect of compound types on the full shape.
3. We don't need to complicate tests for cases without compound data types by requiring the building of a manager, passing it, or finding the builder.

2025-02-13 19:45 UTC, h-mayorquin commented on tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_models/test_dataset_io_configuration_helpers.py
Most of those tests are for the infrastructure that sustains the desired behavior and is not clear to me how they used to fail before this PR. Can you do something like:

```
from neuroconv.tools.nwb_helpers import HDF5DatasetIOConfiguration

nwbfile = mock_NWBFile()
imaging_plane = mock_ImagingPlane(nwbfile=nwbfile)
plane_segmentation = PlaneSegmentation(
    name="PlaneSegmentation",
    description="description",
    imaging_plane=imaging_plane,
)
pixel_mask = [[0, 0, 1]]
plane_segmentation.add_roi(pixel_mask=pixel_mask)
nwbfile.processing["ophys"].add(plane_segmentation)

neurodata_object = plane_segmentation.columns[1]


manager = get_manager()
builder = manager.build(nwbfile)
dst_config = HDF5DatasetIOConfiguration.from_neurodata_object(
    neurodata_object=neurodata_object,
    dataset_name="data",
   builder=builder,
)
assert dst_config.full_shape == (1, )
``


or these the `get_full_shape_function`  instead of the `HDF5DatasetIOConfiguration.from_neurodata_object` (see main comment)

2025-02-17 17:44 UTC, pauladkisson commented on tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_models/test_dataset_io_configuration_helpers.py
> +def test_find_location_in_memory_nwbfile():
> we don't have them somewhere else?

Nope, no dedicated unit tests, so I figured I would take the opportunity to make some.

2025-02-17 18:44 UTC, pauladkisson commented on tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_models/test_dataset_io_configuration_helpers.py
tests/test_minimal/test_tools_hdmf.py: test_get_full_data_shape_compound should accomplish what you're asking for here.

2025-02-17 19:07 UTC, h-mayorquin commented on tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_models/test_dataset_io_configuration_model.py
> +    manager = get_manager()
Do we still need this here after making the builder optional?

2025-02-17 19:08 UTC, h-mayorquin commented on tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_models/test_dataset_io_configuration_helpers.py
> +def test_find_location_in_memory_nwbfile():
OK, makes sense. 
Thanks.

2025-02-17 19:59 UTC, pauladkisson commented on tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_models/test_dataset_io_configuration_model.py
> +    manager = get_manager()
Not strictly speaking, so I made one version of the test with a builder and one without.

2025-02-17 20:06 UTC, h-mayorquin commented on tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_models/test_dataset_io_configuration_model.py
> +    manager = get_manager()
How are you thinking about it? 
If you are testing consistency between passing builder and not builder shouldn't they be the same test to see that the output is the same?

To be honest I was just thinking in not having a test for the builder at this level. This behavior does not dependent on it (it is only relevant for compound data types) but maybe I am missing something, how are you thinking?

2025-02-17 20:17 UTC, pauladkisson commented on tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_models/test_dataset_io_configuration_model.py
> +    manager = get_manager()
I added it for completeness (testing all the paths that the code could travel through), but honestly I agree that not having a test for builder behavior at this level is fine since it will be tested at the `get_default_dataset_io_configurations` level and at the `get_full_data_shape` level.

2025-02-17 20:20 UTC, h-mayorquin approved these changes
LGTM

Should we, in another PR, increase the floor of the hdmf version? Remove the ceiling?

2025-02-17 20:25 UTC, pauladkisson commented
> Should we, in another PR, increase the floor of the hdmf version? Remove the ceiling?

Sure, can you take care of that?

2025-02-17 21:13 UTC, h-mayorquin commented
@pauladkisson 
I can take care of the ceiling but I am not certain if we should increase the floor. Any idea?

2025-02-17 21:18 UTC, pauladkisson commented
> I can take care of the ceiling but I am not certain if we should increase the floor. Any idea?

I don't think we need to as long as it remains compatible with spikeinterface, etc.

2025-02-17 22:12 UTC, merged