Support multi probe and multi trigger structure in spikeglx
catalystneuro/neuroconv pull request #1150
Opened 2024-12-04 16:42 UTC by h-mayorquin

This should fix https://github.com/catalystneuro/neuroconv/issues/978  and #1149

2024-12-05 14:44 UTC, h-mayorquin commented on src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxconverter.py
> -        for stream in streams:
This is the critical part of this. Previously, the Converter assumed a fix structure of the files. This PR gets rids of that assumption.

2024-12-05 14:46 UTC, h-mayorquin commented on src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
> +        file_path: Optional[FilePath] = None,
I would like to deprecate this but I don't want this discussion to get in the way of this PR. If people who review this agree we could start a soft deprecation as we usually do.

Reminder: Spiekinterface takes folder path as input (as in this PR) and not file_path as we currently do in main.

2024-12-05 14:54 UTC, h-mayorquin commented on tests/test_on_data/ecephys/test_spikeglx_converter.py
> +    electrical_series = nwbfile.acquisition["ElectricalSeriesAP"]
Previously, the Converter always writes the ElectricalSeries using the name `f"ElectricalSeriesAPImec{probe_index}"` whereas the interface uses the name `ElectricalSeriesAP` only. This PR makes the behavior of the converter and the interface consistent in the single probe case hence the change.

2024-12-06 16:13 UTC, h-mayorquin commented
The failing test is unrelated to this and should be fixed by #1151

2024-12-09 16:17 UTC, bendichter commented on CHANGELOG.md
> +* `SpikeGLXRecordingInterface` now also accepts `folder_path` making its behavior requivalent to SpikeInterface [#1150](https://github.com/catalystneuro/neuroconv/pull/1150)
```suggestion
* `SpikeGLXRecordingInterface` now also accepts `folder_path` making its behavior equivalent to SpikeInterface [#1150](https://github.com/catalystneuro/neuroconv/pull/1150)
```

2024-12-09 16:19 UTC, bendichter commented on src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
> +        file_path: Optional[FilePath] = None,
Let's preserve the order of the args so we do not cause a breaking change for ordered args

2024-12-09 16:21 UTC, bendichter commented on src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxnidqinterface.py
> +        file_path: Optional[FilePath] = None,
same here, let's keep file_path as the first arg for now

2024-12-09 16:24 UTC, bendichter approved these changes

2024-12-09 16:25 UTC, bendichter requested changes
minor fixes

2024-12-09 20:33 UTC, h-mayorquin commented on src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
> +            self.stream_id = stream_id
SpikeInterface already throws an error that is similar, example:

![image](https://github.com/user-attachments/assets/99e3dd70-179c-4cca-aabf-1847e588fa56)

Does this work or would you like something more specific?

2024-12-10 06:24 UTC, bendichter commented on src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
> +            self.stream_id = stream_id
ok great! Yeah that works

2024-12-10 13:37 UTC, h-mayorquin commented on src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
> +            self.stream_id = stream_id
Anything else missing to merge thigs?

2024-12-10 13:43 UTC, bendichter approved these changes

2024-12-10 15:39 UTC, merged