[Sync II] Add ttl parsing tools
catalystneuro/neuroconv pull request #244
Opened 2022-12-09 21:37 UTC by CodyCBakerPhD

## Motivation
Extension of # that includes tools for parsing the TTL signal to identify the rising and falling frames. Precursor to sync methods of #237.

## How to test the behavior?
Added tests using the synthetic TTLs. Very easy to add new tests for different cases with this approach.

## Checklist

- [X] Have you thoroughly read our [Developer Guide](https://neuroconv.readthedocs.io/en/main/developer_guide.html)?
- [X] Have you ensured the PR description clearly describes the problem and solutions?
- [X] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/catalystneuro/neuroconv/pulls) for the same change?
- [X] If this PR fixes an issue, is the first line of the PR description `fix #XXX` where `XXX` is the issue number?
- [X] Did you update the [CHANGLOG.md](https://github.com/catalystneuro/neuroconv/blob/main/CHANGELOG.md) file on your branch to describe your changes?

2022-12-10 19:29 UTC, CodyCBakerPhD commented
From https://github.com/catalystneuro/neuroconv/pull/237#discussion_r1044871549,

I'd say given the amount of common pre-processing involved in calculating both, as well as the fact that future extensions of this work to harnessing TTL durations and values for decoding digital words, there's no harm at all in calculating both and only using one when needed. The extra `np.where` step, even on a long series, is not such a slow down that it would be cumbersome relative to the total time of parsing the rest of the TTL.

2022-12-23 02:03 UTC, bendichter requested changes

2022-12-23 02:03 UTC, bendichter commented on tests/test_minimal/test_tools/test_signal_processing.py
> +        rising_frames, falling_frames = parse_rising_and_falling_frames_from_ttl(trace=ttl_signal)
can you test the falling_frames is empty?

2023-01-08 23:02 UTC, CodyCBakerPhD commented on tests/test_minimal/test_tools/test_signal_processing.py
> +        ttl_signal = generate_mock_ttl_signal()
Added a new test for this.

One with explicitly set values corresponding to the current default values.

The other that actually tests the default call (no arguments passed) to the function matches our expectations.

2023-01-08 23:02 UTC, CodyCBakerPhD commented on src/neuroconv/tools/signal_processing.py
> +    eps = 1 if np.issubdtype(trace.dtype, np.integer) else np.finfo(float).eps
Adjusted to use the midpoint by default, and also allowing `bins` to be set explicitly if the user wants to assume manual control or use a custom threshold

2023-01-08 23:02 UTC, CodyCBakerPhD commented on src/neuroconv/tools/signal_processing.py
> +def parse_rising_and_falling_frames_from_ttl(trace: np.ndarray, num_bins: int = 2) -> Tuple[np.ndarray, np.ndarray]:
Is now two functions

2023-01-08 23:02 UTC, CodyCBakerPhD commented on src/neuroconv/tools/signal_processing.py
> +def parse_rising_and_falling_frames_from_ttl(trace: np.ndarray, num_bins: int = 2) -> Tuple[np.ndarray, np.ndarray]:
Adjusted to simple 'get'

2023-01-08 23:51 UTC, bendichter commented on CHANGELOG.md
> +* Added a tool for determining rising and falling frames from TTL signals (`parse_rising_and_falling_frames_from_ttl`). [PR #244](https://github.com/catalystneuro/neuroconv/pull/244)
```suggestion
* Added a tool for determining rising and falling frames from TTL signals (`parse_rising_frames_from_ttl` and `get_falling_frames_from_ttl`). [PR #244](https://github.com/catalystneuro/neuroconv/pull/244)
```

2023-01-09 00:05 UTC, bendichter commented on src/neuroconv/tools/signal_processing.py
> +    return rising_frames
```suggestion
def get_rising_frames_from_ttl(trace: np.ndarray, threshold: float = None) -> np.ndarray:
    """
    Return the frame indices for rising events in a TTL pulse.
    
    Parameters
    ----------
    trace : numpy.ndarray
        A TTL pulse.
    
    threshold : float, optional
        The mean of trace is used by default.
    
    Returns
    -------
    numpy.ndarray
        The frame indices of rising events.
    """
    
    if threshold is None:
        threshold = np.mean(trace)
        
    return np.where(np.diff(np.sign(trace - threshold)) > 0)[0] + 1
```

@CodyCBakerPhD is there anything wrong this this simpler version of the function?

2023-01-09 00:06 UTC, bendichter commented on src/neuroconv/tools/signal_processing.py
> +def get_falling_frames_from_ttl(trace: np.ndarray, bins: Optional[np.ndarray] = None) -> Tuple[np.ndarray, np.ndarray]:
```suggestion
def get_falling_frames_from_ttl(trace: np.ndarray, bins: Optional[np.ndarray] = None) -> np.ndarray:
```

2023-01-09 16:50 UTC, bendichter commented on src/neuroconv/tools/signal_processing.py
> +    rising_frames = np.where(diff > 0)[0]
```suggestion
    rising_frames = np.where(diff > 0)[0] + 1
```

I think you need to add one here. take a look at a simple trace e.g. `[-1, -1, 1]` to see

2023-01-09 16:50 UTC, bendichter commented on src/neuroconv/tools/signal_processing.py
> +    falling_frames = np.where(diff < 0)[0]
```suggestion
    falling_frames = np.where(diff < 0)[0] + 1
```

2023-01-09 17:44 UTC, bendichter requested changes
see comment

2023-01-09 17:45 UTC, bendichter commented on src/neuroconv/tools/signal_processing.py
> +    threshold = threshold or np.mean(trace)
```suggestion
    if threshold is None:
         threshold = np.mean(trace)
```

2023-01-09 17:45 UTC, bendichter commented on src/neuroconv/tools/signal_processing.py
> +        The mean of the trace is used by default.
```suggestion
    trace : numpy.ndarray
        A TTL pulse.
    threshold : float, optional
        The threshold used to distinguish on/off states in the trace.
        The mean of the trace is used by default.
```

2023-01-09 17:45 UTC, bendichter commented on src/neuroconv/tools/signal_processing.py
> +    threshold: float, optional
```suggestion
    trace : numpy.ndarray
        A TTL pulse.
    threshold : float, optional
```

2023-01-09 17:45 UTC, bendichter commented on src/neuroconv/tools/signal_processing.py
> +        A TTL pulse.
```suggestion
        A TTL signal.
```

2023-01-09 17:46 UTC, bendichter commented on src/neuroconv/tools/signal_processing.py
> +        A TTL pulse.
```suggestion
        A TTL signal.
```

2023-01-09 17:49 UTC, bendichter commented on src/neuroconv/tools/signal_processing.py
> +    rising_frames: numpy.ndarray
```suggestion
    rising_frames : numpy.ndarray
```

2023-01-09 17:49 UTC, bendichter commented on src/neuroconv/tools/signal_processing.py
> +    falling_frames: numpy.ndarray
```suggestion
    falling_frames : numpy.ndarray
```

2023-01-09 18:24 UTC, bendichter approved these changes

2023-01-09 18:55 UTC, merged